// Generated by CoffeeScript 1.10.0
(function() {
  var ChatClient, ChatController, WebSocketService, ftChat;

  ftChat = angular.module('ft_chat', []);

  ftChat.factory('webSocket', WebSocketService = (function() {
    function WebSocketService(endpoint) {
      this.socket = new WebSocket('ws://' + endpoint + '/chat');
    }

    WebSocketService.prototype.onOpen = function(callback) {
      return this.socket.onopen = callback;
    };

    WebSocketService.prototype.onError = function(callback) {
      return this.socket.onerror = callback;
    };

    WebSocketService.prototype.onMessage = function(callback) {
      return this.socket.onmessage = function(evt) {
        return callback(JSON.parse(evt.data));
      };
    };

    WebSocketService.prototype.send = function(message) {
      return this.socket.send(JSON.strinfigy(message));
    };

    return WebSocketService;

  })());

  ChatClient = (function() {
    ChatClient.property({
      CONNECTED: 'connected'
    });

    function ChatClient($ws) {
      this.$ws = $ws;
      this.$ws.onOpen((function(_this) {
        return function() {
          return _this.status = ChatClient.CONNECTED;
        };
      })(this));
    }

    return ChatClient;

  })();

  ftChat.controller('ChatController', [
    'webSocket', ChatController = (function() {
      function ChatController($webSocket) {
        this.$webSocket = $webSocket;
        this.messages = [];
        this.$websocket.onMessage;
      }

      return ChatController;

    })()
  ]);

}).call(this);
